# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/nogard/Dropbox/Documents/EPICSTUFF/EPICpy/EPICpy/src/main/python/uifiles/loadui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogLoading(object):
    def setupUi(self, DialogLoading):
        DialogLoading.setObjectName("DialogLoading")
        DialogLoading.resize(480, 112)
        DialogLoading.setMinimumSize(QtCore.QSize(480, 112))
        DialogLoading.setMaximumSize(QtCore.QSize(480, 112))
        DialogLoading.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.layoutWidget = QtWidgets.QWidget(DialogLoading)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 90))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelImage = QtWidgets.QLabel(self.layoutWidget)
        self.labelImage.setMinimumSize(QtCore.QSize(78, 80))
        self.labelImage.setMaximumSize(QtCore.QSize(80, 80))
        self.labelImage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelImage.setFrameShape(QtWidgets.QFrame.Box)
        self.labelImage.setText("")
        self.labelImage.setScaledContents(True)
        self.labelImage.setObjectName("labelImage")
        self.horizontalLayout.addWidget(self.labelImage)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelText = QtWidgets.QLabel(self.layoutWidget)
        self.labelText.setMinimumSize(QtCore.QSize(370, 55))
        self.labelText.setMaximumSize(QtCore.QSize(370, 9999))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelText.setFont(font)
        self.labelText.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelText.setAlignment(QtCore.Qt.AlignCenter)
        self.labelText.setWordWrap(True)
        self.labelText.setObjectName("labelText")
        self.verticalLayout.addWidget(self.labelText)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(DialogLoading)
        QtCore.QMetaObject.connectSlotsByName(DialogLoading)

    def retranslateUi(self, DialogLoading):
        _translate = QtCore.QCoreApplication.translate
        DialogLoading.setWindowTitle(_translate("DialogLoading", "Dialog"))
        self.labelText.setText(_translate("DialogLoading", "Loading, Please Wait..."))
