# Form implementation generated from reading ui file '/home/nogard/Dropbox/Documents/EPICSTUFF/EPICpy2/EPICpy2_pyqt6/epicpy/uifiles/breaksettingsui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogRuleBreak(object):
    def setupUi(self, DialogRuleBreak):
        DialogRuleBreak.setObjectName("DialogRuleBreak")
        DialogRuleBreak.resize(593, 644)
        DialogRuleBreak.setMinimumSize(QtCore.QSize(593, 644))
        DialogRuleBreak.setMaximumSize(QtCore.QSize(3001, 3001))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        DialogRuleBreak.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(parent=DialogRuleBreak)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 621))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxEnableRuleBreaks = QtWidgets.QCheckBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.checkBoxEnableRuleBreaks.setFont(font)
        self.checkBoxEnableRuleBreaks.setObjectName("checkBoxEnableRuleBreaks")
        self.verticalLayout.addWidget(self.checkBoxEnableRuleBreaks)
        self.listWidgetRules = QtWidgets.QListWidget(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        self.listWidgetRules.setFont(font)
        self.listWidgetRules.setObjectName("listWidgetRules")
        self.verticalLayout.addWidget(self.listWidgetRules)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            368,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.pushButtonOK = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.pushButtonOK.setFont(font)
        self.pushButtonOK.setDefault(True)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout.addWidget(self.pushButtonOK)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogRuleBreak)
        QtCore.QMetaObject.connectSlotsByName(DialogRuleBreak)

    def retranslateUi(self, DialogRuleBreak):
        _translate = QtCore.QCoreApplication.translate
        DialogRuleBreak.setWindowTitle(
            _translate("DialogRuleBreak", "Rule Break Settings")
        )
        self.checkBoxEnableRuleBreaks.setText(
            _translate("DialogRuleBreak", "Enable Rule Breaks?")
        )
        self.pushButtonCancel.setText(_translate("DialogRuleBreak", "Cancel"))
        self.pushButtonOK.setText(_translate("DialogRuleBreak", "OK"))
