# Form implementation generated from reading ui file '/home/nogard/Dropbox/Documents/EPICSTUFF/EPICpy2/EPICpy2_pyqt6/epicpy/uifiles/loggingui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_DialogLoggingSettings(object):
    def setupUi(self, DialogLoggingSettings):
        DialogLoggingSettings.setObjectName("DialogLoggingSettings")
        DialogLoggingSettings.resize(708, 300)
        DialogLoggingSettings.setMinimumSize(QtCore.QSize(708, 300))
        DialogLoggingSettings.setMaximumSize(QtCore.QSize(3000, 3000))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(12)
        DialogLoggingSettings.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(parent=DialogLoggingSettings)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 16, 681, 273))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(12)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBoxLogNormalOut = QtWidgets.QCheckBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(12)
        font.setBold(True)
        self.checkBoxLogNormalOut.setFont(font)
        self.checkBoxLogNormalOut.setObjectName("checkBoxLogNormalOut")
        self.horizontalLayout_2.addWidget(self.checkBoxLogNormalOut)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.toolButtonNormalOut = QtWidgets.QToolButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(12)
        font.setBold(True)
        self.toolButtonNormalOut.setFont(font)
        self.toolButtonNormalOut.setObjectName("toolButtonNormalOut")
        self.horizontalLayout_2.addWidget(self.toolButtonNormalOut)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.plainTextEditNormalOutFile = QtWidgets.QPlainTextEdit(
            parent=self.layoutWidget
        )
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(12)
        self.plainTextEditNormalOutFile.setFont(font)
        self.plainTextEditNormalOutFile.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhMultiLine
            | QtCore.Qt.InputMethodHint.ImhNoAutoUppercase
        )
        self.plainTextEditNormalOutFile.setPlainText("")
        self.plainTextEditNormalOutFile.setObjectName("plainTextEditNormalOutFile")
        self.verticalLayout.addWidget(self.plainTextEditNormalOutFile)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxLogTraceOut = QtWidgets.QCheckBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(12)
        font.setBold(True)
        self.checkBoxLogTraceOut.setFont(font)
        self.checkBoxLogTraceOut.setObjectName("checkBoxLogTraceOut")
        self.horizontalLayout_3.addWidget(self.checkBoxLogTraceOut)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_3.addItem(spacerItem1)
        self.toolButtonTraceOut = QtWidgets.QToolButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(12)
        font.setBold(True)
        self.toolButtonTraceOut.setFont(font)
        self.toolButtonTraceOut.setObjectName("toolButtonTraceOut")
        self.horizontalLayout_3.addWidget(self.toolButtonTraceOut)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.plainTextEditTraceOutFile = QtWidgets.QPlainTextEdit(
            parent=self.layoutWidget
        )
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(12)
        self.plainTextEditTraceOutFile.setFont(font)
        self.plainTextEditTraceOutFile.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhMultiLine
            | QtCore.Qt.InputMethodHint.ImhNoAutoUppercase
        )
        self.plainTextEditTraceOutFile.setPlainText("")
        self.plainTextEditTraceOutFile.setObjectName("plainTextEditTraceOutFile")
        self.verticalLayout.addWidget(self.plainTextEditTraceOutFile)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.pushButtonCancel = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.pushButtonCancel
        )
        self.pushButtonOK = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButtonOK.setFont(font)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButtonOK
        )
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogLoggingSettings)
        QtCore.QMetaObject.connectSlotsByName(DialogLoggingSettings)

    def retranslateUi(self, DialogLoggingSettings):
        _translate = QtCore.QCoreApplication.translate
        DialogLoggingSettings.setWindowTitle(
            _translate("DialogLoggingSettings", "Output Logging Settings")
        )
        self.checkBoxLogNormalOut.setText(
            _translate("DialogLoggingSettings", "Log Normal Output?")
        )
        self.toolButtonNormalOut.setText(_translate("DialogLoggingSettings", "..."))
        self.checkBoxLogTraceOut.setText(
            _translate("DialogLoggingSettings", "Log Trace Output?")
        )
        self.toolButtonTraceOut.setText(_translate("DialogLoggingSettings", "..."))
        self.pushButtonCancel.setText(_translate("DialogLoggingSettings", "Cancel"))
        self.pushButtonOK.setText(_translate("DialogLoggingSettings", "OK"))
