# Form implementation generated from reading ui file '/home/nogard/Dropbox/Documents/EPICSTUFF/EPICpy2/EPICpy2_pyqt6/epicpy/uifiles/searchui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_DialogSearch(object):
    def setupUi(self, DialogSearch):
        DialogSearch.setObjectName("DialogSearch")
        DialogSearch.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        DialogSearch.resize(702, 245)
        DialogSearch.setMinimumSize(QtCore.QSize(702, 242))
        DialogSearch.setMaximumSize(QtCore.QSize(3000, 3000))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        DialogSearch.setFont(font)
        DialogSearch.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(DialogSearch)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=DialogSearch)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEditSearchText = QtWidgets.QLineEdit(parent=DialogSearch)
        self.lineEditSearchText.setClearButtonEnabled(True)
        self.lineEditSearchText.setObjectName("lineEditSearchText")
        self.verticalLayout.addWidget(self.lineEditSearchText)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.checkBoxRegEx = QtWidgets.QCheckBox(parent=DialogSearch)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.checkBoxRegEx.setFont(font)
        self.checkBoxRegEx.setObjectName("checkBoxRegEx")
        self.verticalLayout_2.addWidget(self.checkBoxRegEx)
        self.checkBoxIgnoreCase = QtWidgets.QCheckBox(parent=DialogSearch)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.checkBoxIgnoreCase.setFont(font)
        self.checkBoxIgnoreCase.setObjectName("checkBoxIgnoreCase")
        self.verticalLayout_2.addWidget(self.checkBoxIgnoreCase)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            388,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(parent=DialogSearch)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.pushButtonSearchBackward = QtWidgets.QPushButton(parent=DialogSearch)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.pushButtonSearchBackward.setFont(font)
        self.pushButtonSearchBackward.setDefault(False)
        self.pushButtonSearchBackward.setObjectName("pushButtonSearchBackward")
        self.horizontalLayout.addWidget(self.pushButtonSearchBackward)
        self.pushButtonSearchForward = QtWidgets.QPushButton(parent=DialogSearch)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.pushButtonSearchForward.setFont(font)
        self.pushButtonSearchForward.setDefault(True)
        self.pushButtonSearchForward.setObjectName("pushButtonSearchForward")
        self.horizontalLayout.addWidget(self.pushButtonSearchForward)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(DialogSearch)
        QtCore.QMetaObject.connectSlotsByName(DialogSearch)

    def retranslateUi(self, DialogSearch):
        _translate = QtCore.QCoreApplication.translate
        DialogSearch.setWindowTitle(_translate("DialogSearch", "Specify Which Text To Search For"))
        self.label.setText(_translate("DialogSearch", "Search For:"))
        self.checkBoxRegEx.setText(_translate("DialogSearch", "Treat as Regular Expression?"))
        self.checkBoxIgnoreCase.setText(_translate("DialogSearch", "Ignore Case?"))
        self.pushButtonCancel.setText(_translate("DialogSearch", "Cancel"))
        self.pushButtonSearchBackward.setText(_translate("DialogSearch", "Search\n" "Backward"))
        self.pushButtonSearchForward.setText(_translate("DialogSearch", "Search\n" "Forward"))
