# Form implementation generated from reading ui file '/home/nogard/Dropbox/Documents/EPICSTUFF/EPICpy2/EPICpy2_pyqt6/epicpy/uifiles/statsui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_StatsWindow(object):
    def setupUi(self, StatsWindow):
        StatsWindow.setObjectName("StatsWindow")
        StatsWindow.resize(660, 545)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        StatsWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=StatsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.statsTextBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.statsTextBrowser.setGeometry(QtCore.QRect(10, 10, 640, 480))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.statsTextBrowser.setFont(font)
        self.statsTextBrowser.setAcceptDrops(False)
        self.statsTextBrowser.setOpenExternalLinks(True)
        self.statsTextBrowser.setObjectName("statsTextBrowser")
        StatsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=StatsWindow)
        self.statusbar.setObjectName("statusbar")
        StatsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StatsWindow)
        QtCore.QMetaObject.connectSlotsByName(StatsWindow)

    def retranslateUi(self, StatsWindow):
        _translate = QtCore.QCoreApplication.translate
        StatsWindow.setWindowTitle(_translate("StatsWindow", "Stats Output Window"))
