# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/nogard/Dropbox/Documents/EPICSTUFF/EPICpy/EPICpy/src/main/python/uifiles/texteditorui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextEditorChooser(object):
    def setupUi(self, TextEditorChooser):
        TextEditorChooser.setObjectName("TextEditorChooser")
        TextEditorChooser.resize(818, 400)
        TextEditorChooser.setMinimumSize(QtCore.QSize(708, 300))
        TextEditorChooser.setMaximumSize(QtCore.QSize(3000, 3000))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        TextEditorChooser.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(TextEditorChooser)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(TextEditorChooser)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonBuiltIn = QtWidgets.QRadioButton(TextEditorChooser)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonBuiltIn.setFont(font)
        self.radioButtonBuiltIn.setIconSize(QtCore.QSize(24, 24))
        self.radioButtonBuiltIn.setChecked(True)
        self.radioButtonBuiltIn.setObjectName("radioButtonBuiltIn")
        self.horizontalLayout_2.addWidget(self.radioButtonBuiltIn)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButtonDefault = QtWidgets.QRadioButton(TextEditorChooser)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonDefault.setFont(font)
        self.radioButtonDefault.setIconSize(QtCore.QSize(24, 24))
        self.radioButtonDefault.setObjectName("radioButtonDefault")
        self.horizontalLayout_3.addWidget(self.radioButtonDefault)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonOK = QtWidgets.QPushButton(TextEditorChooser)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOK.setFont(font)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout.addWidget(self.pushButtonOK)
        self.pushButtonCancel = QtWidgets.QPushButton(TextEditorChooser)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(TextEditorChooser)
        QtCore.QMetaObject.connectSlotsByName(TextEditorChooser)

    def retranslateUi(self, TextEditorChooser):
        _translate = QtCore.QCoreApplication.translate
        TextEditorChooser.setWindowTitle(
            _translate("TextEditorChooser", "Text Editor Choice Dialog")
        )
        self.label_2.setText(
            _translate(
                "TextEditorChooser",
                "<html><head/><body><p>Some EPICpy features require a text editor (e.g., those available when you right-click the Normal Output Window). We recommend you use the BUILT-IN version of EPICcoder so that production rule files get colorful syntax-highlighting. However, EPICcoder is a rather minimal editor, so if you have another text-editor you would rather use (e.g., Atom, Sublimetext, etc.), select SYSTEM-DEFAULT below and EPICpy will use whatever text-editor you have associated with .prs and .txt files in your operating system.</p></body></html>",
            )
        )
        self.radioButtonBuiltIn.setText(
            _translate(
                "TextEditorChooser",
                "Use Built-In EPICcoder Editor for .prs and .txt Files",
            )
        )
        self.radioButtonDefault.setText(
            _translate(
                "TextEditorChooser", "Use System Default Editor for .prs and .txt Files"
            )
        )
        self.pushButtonOK.setText(_translate("TextEditorChooser", "OK"))
        self.pushButtonCancel.setText(_translate("TextEditorChooser", "Cancel"))
